# Assignment 1: Python Fundamentals, NumPy, and Pandas
---

*Please run this notebook from top to bottom, as some cells depend on variables defined earlier*

## Task 1: A list of dictionaries

### a) Filter out invalid transactions where the price is zero or the quantity is negative.

In [4]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

# Removes transactions where price equals zero or quantity is negative
for i in transactions[:]:
    if i["price"] == 0 or i["quantity"] < 0:
        transactions.remove(i)

# Prints the remaining transactions
print("Remaining transactions:")
for i in transactions:
    print(i)

Remaining transactions:
{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}
{'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}
{'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}
{'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}

### b) For each remaining transaction, compute a new field `total` = `price * quantity`.

In [5]:
# Adds new field total (price * quantity)
for i in transactions:
    i["total"] = i["price"] * i["quantity"]
    print(i)

{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}
{'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}
{'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}
{'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}

### c) Group the valid transactions by `region` and compute the total revenue per region. Store the result in a dictionary.

In [6]:
revenue_per_region = {}

# Creates keys for each region in a dictionary
for i in transactions:
    region = i["region"]
    region_revenue = i["total"]
    
    # Assigns a temporary value to each key
    revenue_per_region[region] = 0

# Loops through all regions and computes the total revenue for each region
for i in transactions:
    region = i["region"]
    region_revenue = i["total"]

    revenue_per_region[region] = revenue_per_region[region] + region_revenue

print(f"Total revenue per region:\n{revenue_per_region}")

Total revenue per region:
{'EU': 3600, 'US': 1050, 'APAC': 750}

### d) Print the region with the highest total revenue and its value using an f-string.

In [7]:
highest_value = 0
region_highest_value = ""

# Loops through all regions and assigns the highest values and the corresponding region to variables
for region, value in revenue_per_region.items():
    if highest_value < value:
        highest_value = value
        region_highest_value = region

print(f"Region with the highest value: {region_highest_value} ({highest_value})")

Region with the highest value: EU (3600)

---
## Task 2: Creating a function

In [189]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

def summarise_sales(sales:list):
    total = sum(sales)

    average = round((total / len(sales)), 2) # Returns the mean daily sales value and rounds to two decimals
    
    # Loops through the list and returns the index of the day with the highest and lowest sales
    day_index = 0
    best_day_value = 0
    worst_day_value = max(sales) # Temporarily assigns the worst_day_value to the highest value in the list
    
    for day in sales:
        day_index += 1

        # Assigns the best day
        if day > best_day_value:
            best_day_value = day
            best_day = day_index

        # Assigns the worst day
        if day < worst_day_value:
            worst_day_value = day
            worst_day = day_index

    # Loops through the list and returns the amount of days where sales exceed the average
    above_average_count = 0
    for day in sales:
        if day > average:
            above_average_count += 1

    summarised_sales = {
        "total": total,
        "average": average,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": above_average_count
    }

    return summarised_sales

print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}

---
## Task 3: Loops

### a) Create a new list called `passing` that contains only the names of students with a grade of 50 or above. Print the list.

In [16]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

passing = []

# Loops through the students list and appends students with a grade of 50 or above to passing list
for i in students:
    name = i["name"]
    grade = i["grade"]
    
    if grade >= 50:
        passing.append(name)

print(f"List of passing students:\n{passing}")

List of passing students:
['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']

### b) Loop through the students and print a status message for each. If the student's grade is 80 or above, print `"[name]: Excellent"`; if between 50 and 79, print `"[name]: Pass"`; otherwise print `"[name]: Fail"`.

In [20]:
for i in students:
    name = i["name"]
    grade = i["grade"]

    # Checks in which range the students grade is and assigns the status message to status_message
    if grade >= 80:
        status_message = "Excellent"
    elif grade >= 50:
        status_message = "Pass"
    else:
        status_message = "Fail"
    
    print(f"{name}: {status_message}")

Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass

### c) Count how many students have an attendance rate below 0.80. Print the count.

In [22]:
attendance_count = 0

# Loops through the students and counts the amount that have an attendance rate below 0.8
for i in students:
    attendance = i["attendance"]

    if attendance < 0.80:
        attendance_count += 1
    
print(f"Amount of students with an attendance rate below 0.80: {attendance_count}")

Amount of students with an attendance rate below 0.80: 4

### d) Find the student with the highest grade using a loop (do not use `max()`). Print the student's name and grade.

In [24]:
best_student = ""
best_student_grade = 0

# Loops through the students and assigns the name and grade of the student with the highest grade
for i in students:
    name = i["name"]
    grade = i["grade"]

    if grade > best_student_grade:
        best_student = name
        best_student_grade = grade

print(f"Student with the highest grade: {best_student} ({best_student_grade})")

Student with the highest grade: Nina (95)

### e) Now find the student with the highest grade using `max()`. Print the student's name and grade.

In [54]:
# max() goes through each student in the list and for each student (x) use x["grade"] to compare grades
best = max(students, key = lambda x: x["grade"])

best_student = best["name"]
best_student_grade = best["grade"]

print(f"Student with the highest grade: {best_student} ({best_student_grade})")

Student with the highest grade: Nina (95)

---
## Task 4: Class and methods

In [250]:
class Portfolio:
    def __init__(self, owner:str):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker:str, shares:float, price_per_share:float):
        
        # Checks if there already exists shares with the same ticker and assigns the amount to current_shares
        current_shares = 0
        for key in self.holdings.keys():
            if key == ticker:
                current_shares = self.holdings[ticker]["shares"]

        shares_data = {}
        shares_data["shares"] = shares + current_shares # Adds the new amount of shares to the old ones
        shares_data["price_per_share"] = price_per_share

        self.holdings[ticker] = shares_data
    
    def total_value(self):
        self.total = 0
        for key, row in self.holdings.items():
            self.total += row["shares"] * row["price_per_share"]
        
        return round(self.total, 2)
    
    def most_valuable(self):
        highest_total_value = 0 # Temporary value
        highest_asset = "" # Temporary value
        
        # Loops through all keys and values, calculates a total value per asset and returns the ticker of the highest total value
        for key, row in self.holdings.items():
            row_value = row["shares"] * row["price_per_share"]
            if row_value > highest_total_value:
                highest_total_value = row_value
                highest_asset = key
        
        return highest_asset

    def __str__(self):
        assets_amount = len(self.holdings.keys())
        total = self.total_value()
        return f"Portfolio summary:\nOwner: {self.owner}\nNumber of assets: {assets_amount}\nTotal value: {total:,.2f}"

model_portfolio = Portfolio("Leander")

model_portfolio.add_asset("NVIDIA", 13, 175.20)
model_portfolio.add_asset("Nokia", 150, 7.28)
model_portfolio.add_asset("NVIDIA", 17, 172.37)
model_portfolio.add_asset("Apple", 15, 251.64)

### a) A method `add_asset(ticker, shares, price_per_share)` that adds a new asset or updates the number of shares if the ticker already exists (in which case the price should also be updated).

In [251]:
model_portfolio.holdings

{'NVIDIA': {'shares': 30, 'price_per_share': 172.37},
 'Nokia': {'shares': 150, 'price_per_share': 7.28},
 'Apple': {'shares': 15, 'price_per_share': 251.64}}

### b) A method `total_value()` that returns the total market value of the portfolio.

In [252]:
model_portfolio.total_value()

10037.7

### c) A method `most_valuable()` that returns the ticker of the asset with the highest total value (shares × price).

In [253]:
model_portfolio.most_valuable()

'NVIDIA'

### d) A `__str__` method that returns a readable summary of the portfolio, including the owner's name, the number of assets, and the total value.

In [254]:
print(model_portfolio)

Portfolio summary:
Owner: Leander
Number of assets: 3
Total value: 10,037.70

## Task 5: Importing a module

In [148]:
import datetime as dt

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

# Sets first_date and last_date to the first date in the orders list temporarily
first_date = dt.date.fromisoformat(orders[0][0])
last_date = dt.date.fromisoformat(orders[0][0])

# Assigns the first and last date to the actual first and last date in the list
for i in orders:
    original_date = i[0]
    date = dt.date.fromisoformat(original_date)
    if date < first_date:
        first_date = date
    if date > last_date:
        last_date = date

days_between_first_last_date = last_date - first_date

print(f"Amount of days between first and last date: {days_between_first_last_date.days}")

Amount of days between first and last date: 80

## Task 6: Array Operations and Broadcasting

### a) Compute and print the total annual revenue for each year (i.e., row sums). Use the `axis` parameter.

In [170]:
import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

start_year = 2022

yearly_total = revenue.sum(axis = 1) * 1000 # Summarizes revenue per year and converts to euros

for i in range(len(yearly_total)):
    year = i + start_year
    
    year_revenue = yearly_total[i]

    print(f"{year}: {year_revenue:,.0f}€")

2022: 880,000€
2023: 950,000€
2024: 1,080,000€

### b) Compute the mean quarterly revenue across all years (i.e., column means).

In [174]:
quarter_mean = revenue.mean(axis = 0) * 1000

for index, i in enumerate(quarter_mean, 1):
    print(f"Q{index}: {i:,.0f}€")

Q1: 226,667€
Q2: 260,000€
Q3: 206,667€
Q4: 276,667€

### c) Using broadcasting, apply a growth adjustment to the 2024 row by multiplying it element-wise with the array `[1.05, 1.03, 1.08, 1.02]`. Print the adjusted values.

In [178]:
growth_adjustment = [1.05, 1.03, 1.08, 1.02]

revenue_2024 = revenue[2]
adjusted_revenue_2024 = revenue_2024 * growth_adjustment * 1000

print("Adjusted revenue 2024:")
for quarter, value in enumerate(adjusted_revenue_2024, start = 1):
    print(f"Q{quarter}: {value:,.0f}€") # Prints the quarters one by one and displays in proper format

Adjusted revenue 2024:
Q1: 262,500€
Q2: 298,700€
Q3: 248,400€
Q4: 316,200€

### d) Use boolean indexing to find and print all quarterly revenue values that exceed 250 (thousands of euros).

In [179]:
print(revenue[revenue > 250])

[260 270 290 310]

## Task 7: Pandas

### a) Add a new column `salary_per_year_exp` computed as `salary / years_exp`. Round to the nearest integer.

In [213]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

employee_data = pd.DataFrame(data)

# Adds column salary_per_year_exp and rounds to the nearest integer
employee_data["salary_per_year_exp"] = (employee_data["salary"] / employee_data["years_exp"]).round().astype(int)

employee_data

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900
1,Erik,Marketing,4000,3,3.8,1333
2,Mia,Finance,4800,7,4.5,686
3,Leo,IT,5200,10,4.0,520
4,Sara,Marketing,3900,2,3.5,1950
5,Tom,IT,5100,8,4.9,638

### b) Sort the DataFrame by `performance_score` in descending order and print the top 3 employees.

In [214]:
# Sorts the DataFrame by performance_score and prints the three first rows
print(employee_data.sort_values(by="performance_score", ascending=False)[:3])

  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9
2      Mia    Finance    4800          7                4.5
0     Anna    Finance    4500          5                4.2

   salary_per_year_exp
5                  638
2                  686
0                  900

### c) Using `.loc`, select all employees in the Finance department with a performance score above 4.0. Print the result.

In [224]:
finance_mask = employee_data["department"] == "Finance"
performance_mask = employee_data["performance_score"] > 4

print(employee_data.loc[finance_mask & performance_mask])

  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2
2      Mia    Finance    4800          7                4.5

   salary_per_year_exp
0                  900
2                  686

### d) Rename the column `years_exp` to `experience_years` using the `.rename()` method.

In [255]:
employee_data = employee_data.rename(columns={"years_exp": "experience_years"})
employee_data

,employee,department,salary,experience_years,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900
1,Erik,Marketing,4000,3,3.8,1333
2,Mia,Finance,4800,7,4.5,686
3,Leo,IT,5200,10,4.0,520
4,Sara,Marketing,3900,2,3.5,1950
5,Tom,IT,5100,8,4.9,638

### e) Using `.iloc`, select and print the salary and performance score columns for the first four employees.

In [227]:
print(employee_data.iloc[:4, [2, 4]])

   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0

## Task 8: More Pandas

### a) Create a DataFrame with columns: `date`, `visitors`, `conversion_rate`, and `avg_order_value`. Set `date` as the index.

In [186]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

# Creates a dictionary with the generated values
data = {
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value,
}

# Creates a DataFrame from the dictionary
website_traffic = pd.DataFrame(data, index= days)
website_traffic

            visitors  conversion_rate  avg_order_value
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39
2025-01-11       288           0.0511            46.07
2025-01-12       302           0.0339            72.90
2025-01-13       273           0.0300            42.82
2025-01-14       333           0.0499            50.33
2025-01-15       270           0.0550            50.28
2025-01-16       339           0.0311            50.28
2025-01-17       524           0.0209            50.55
2025-01-18       380           0.0483            45.18
2025-01-19       569           0.0637            44.17
2025-01-20       379           0.0751            41.38
2025-01-21       310           0.0575            35.12
2025-01-22       515           0.0750            52.16
2025-01-23       527           0.0719            59.84
2025-01-24       544           0.0331            44.57
2025-01-25       555           0.0720            44.41
2025-01-26       210           0.0638            46.84
2025-01-27       405           0.0367            45.39
2025-01-28       307           0.0678            35.64
2025-01-29       297           0.0719            63.65
2025-01-30       296           0.0380            54.39
2025-01-31       529           0.0516            42.88
2025-02-01       516           0.0243            52.97
2025-02-02       285           0.0550            45.62

### b) Compute two new columns: `conversions` (= visitors × conversion_rate, rounded to the nearest integer) and `daily_revenue` (= conversions × avg_order_value).

In [188]:
# Creates column conversions and rounds to nearest integer
website_traffic["conversions"] = (website_traffic["visitors"] * website_traffic["conversion_rate"]).round(0).astype(int)

# Creates column daily_revenue (conversions * avg_order_value)
website_traffic["daily_revenue"] = website_traffic["conversions"] * website_traffic["avg_order_value"]

website_traffic

,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
2025-01-06,206,0.0645,64.30,13,835.90
2025-01-07,472,0.0578,48.44,27,1307.88
2025-01-08,437,0.0756,43.26,33,1427.58
2025-01-09,221,0.0339,43.61,7,305.27
2025-01-10,563,0.0679,49.39,38,1876.82
2025-01-11,288,0.0511,46.07,15,691.05
2025-01-12,302,0.0339,72.90,10,729.00
2025-01-13,273,0.0300,42.82,8,342.56
2025-01-14,333,0.0499,50.33,17,855.61
2025-01-15,270,0.0550,50.28,15,754.20
2025-01-16,339,0.0311,50.28,11,553.08
2025-01-17,524,0.0209,50.55,11,556.05
2025-01-18,380,0.0483,45.18,18,813.24
2025-01-19,569,0.0637,44.17,36,1590.12
2025-01-20,379,0.0751,41.38,28,1158.64
2025-01-21,310,0.0575,35.12,18,632.16
2025-01-22,515,0.0750,52.16,39,2034.24
2025-01-23,527,0.0719,59.84,38,2273.92
2025-01-24,544,0.0331,44.57,18,802.26
2025-01-25,555,0.0720,44.41,40,1776.40
2025-01-26,210,0.0638,46.84,13,608.92
2025-01-27,405,0.0367,45.39,15,680.85
2025-01-28,307,0.0678,35.64,21,748.44
2025-01-29,297,0.0719,63.65,21,1336.65
2025-01-30,296,0.0380,54.39,11,598.29
2025-01-31,529,0.0516,42.88,27,1157.76
2025-02-01,516,0.0243,52.97,13,688.61
2025-02-02,285,0.0550,45.62,16,729.92